return {
{"sainnhe/gruvbox-material",},-- colorscheme},
{"osyo-manga/vim-over",},-- visual find and replace},
{"junegunn/fzf",},-- findfiles},
{"junegunn/fzf.vim"},
{"preservim/nerdtree",},-- navigation},
{"gu-fan/riv.vim",},-- rst},
{"ntpeters/vim-better-whitespace",},-- highlight trailing white space},
{"bkad/CamelCaseMotion",},-- Camelcase Movement},
{"vim-airline/vim-airline"},
{"vim-airline/vim-airline-themes",},-- statusbar},
{"justinmk/vim-sneak",},-- Regex preview},
{"christoomey/vim-tmux-navigator",},-- tmux integration},
{"neoclide/coc.nvim",
branch="master",
build="yarn install --frozen-lockfile"},-- autocomplete},
{"pearofducks/ansible-vim",},-- ansible support},
{"tpope/vim-surround",},-- Surround tools},
{"tpope/vim-commentary",},-- Commenting},
{"nvim-treesitter/nvim-treesitter",},-- Parsers used by render-markdown},
{"MeanderingProgrammer/render-markdown.nvim",},-- Markdown preview in nvim},
{"echasnovski/mini.icons",},-- Icons},
}
