name: PR Workflow

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install UV
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies
        run: |
          uv sync
          echo "✅ Dependencies installed"

      - name: Test help command
        run: |
          uv run dotfiles-init --help > /dev/null
          echo "✅ Help command works"