---
name: PR Validation

"on":
  pull_request:
    branches: [master, main]
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: |
          uv sync
          echo "✅ Dependencies installed"

      - name: Test help command
        run: |
          uv run dotfiles-init --help > /dev/null
          echo "✅ Help command works"

  quick-test:
    name: Quick Container Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Quick test on Arch
        run: |
          chmod +x test/run_tests.sh
          timeout 20m ./test/run_tests.sh --arch --cleanup || true
          echo "✅ Arch container test completed"
